### ISSUE TITLE
Failed to notify project evaluation listener

### ISSUE THREAD

**Issue by hu-qi** [HMS-Core/hms-image-vision-java#3]
org.gradle.api.file.DirectoryProperty org.gradle.api.file.ProjectLayout.directoryProperty(org.gradle.api.provider.Provider)

Hello, I run the project but get error.

![image](https://user-images.githubusercontent.com/17986122/133915205-d94121e1-71d5-44cd-8318-dd2a050e5847.png)

**Comment by Mike-mei** [comment]
Please Refer to the solution in this link: https://stackoverflow.com/questions/44094037/android-studio-failed-to-notify-project-evaluation-listener-error
